package it.unibo.conversational.database

val queries = listOf(
        listOf("sum unit sales by media type for USA as country", "sum unit_sales", "media_type", "country = USA"),
        listOf("store sales by gender", "avg store_sales", "gender", ""),
        listOf("sum unit sales by media type for Sheri Nowmer", "sum unit_sales", "media_type", "fullname = Sheri Nowmer"),
        listOf("sum unit_sales by country by month by province for Sheri Nowmer", "sum unit_sales", "country, the_month, state_province", "fullname = Sheri Nowmer"),
        listOf("store sales by month in 2010 for Atomic Mints USA by store", "avg store_sales", "the_month, store_id", "the_year = 2010 and product_name = Atomic Mints"),
        listOf("sum unit sales by month for 2010 as year", "sum unit_sales", "the_month", "the_year = 2010"),
        listOf("sum unit sales", "sum unit_sales", "", ""),
        listOf("store sales by country", "avg store_sales", "country", ""),
        listOf("store sales by fullname Sheri Nowmer", "avg store_sales", "", "fullname = Sheri Nowmer"),
        listOf("store sales by gender for USA as country", "avg store_sales", "gender", "country = USA"),
        listOf("store sales by gender for Sheri Nowmer", "avg store_sales", "gender", "fullname = Sheri Nowmer"),
        listOf("sum unit sales by media type for USA as country", "sum unit_sales", "media_type", "country = USA"),
        listOf("sum unit sales by media type", "sum unit_sales", "media_type", ""),
        listOf("sum unit sales for Club Chocolate Milk", "sum unit_sales", "", "product_name = Club Chocolate Milk "),
        listOf("sum store cost by country for USA as country", "sum store_cost", "country", "country = USA"),
        listOf("store sales by Club Chocolate Milk", "avg store_sales", "", "product_name = Club Chocolate Milk "),
        listOf("sum store cost for Canada as country", "sum store_cost", "", "country = Canada"),
        listOf("store sales by year media type", "avg store_sales", "the_year, media_type", ""),
        listOf("store sales by year", "avg store_sales", "the_year", ""),
        listOf("sum unit sales by gender", "sum unit_sales", "gender", ""),
        listOf("store sales for Club Chocolate Milk as product name", "avg store_sales", "", "product_name = Club Chocolate Milk "),
        listOf("sum unit sales by country for Mexico as country", "sum unit_sales", "country", "country = Mexico"),
        listOf("sum unit sales for Mexico as country", "sum unit_sales", "", "country = Mexico"),
        listOf("sum unit sales by country for 2015 as year", "sum unit_sales", "country", "the_year = 2015"),
        listOf("units by country for 2015 as year", "sum unit_sales", "country", "the_year = 2015"),
        listOf("sum unit sales by country", "sum unit_sales", "country", ""),
        listOf("count sales in 1990", "count sales_fact_1997", "", "the_year = 1990"),
        listOf("count sales in 1990 by country", "count sales_fact_1997", "country", "the_year = 1990"),
        listOf("sum unit sales by country for Mexico as country", "sum unit_sales", "country", "country = Mexico"),
        listOf("sum unit sales by country", "sum unit_sales", "country", ""),
        listOf("count sales by country", "count sales_fact_1997", "country", ""),
        listOf("count sales", "count sales_fact_1997", "", ""),
        listOf("sum store costs by country for Jalisco as province", "sum store_cost", "country", "state_province = Jalisco"),
        listOf("sum store costs", "sum store_cost", "", ""),
        listOf("sum store costs by month", "sum store_cost", "the_month", ""),
        listOf("sum unit sales by country", "sum unit_sales", "country", ""),
        listOf("sum unit sales by country product name", "sum unit_sales", "country, product_name", ""),
        listOf("sum store costs by year", "sum store_cost", "country", ""),
        listOf("sum store costs by country for 2015 as year", "sum store_cost", "country", "the_year = 2015"),
        listOf("product sum store costs and sum unit sales for 2013", "sum store_cost, sum unit_sales", "product_id", "the_year = 2013"),
        listOf("count sales 1997 by country", "count sales_fact_1997", "country", ""),
        listOf("count sales 1997", "count sales_fact_1997", "", ""),
        listOf("sum unit sales by media type for Sheri Nowmer", "sum unit_sales", "media_type", "fullname = Sheri Nowmer"),
        listOf("sum unit sales by media type for USA as country", "sum unit_sales", "media_type", "country = USA"),
        listOf("sum unit sales by media type for Sheri Nowmer", "sum unit_sales", "media_type", "fullname = Sheri Nowmer"),
        listOf("sum unit sales by media type for USA as country gender", "sum unit_sales", "media_type", "country = USA"),
        listOf("store sales by year", "avg store_sales", "the_year", ""),
        listOf("store sales", "avg store_sales", "", ""),
        listOf("product sum store costs and sum unit sales for 2013", "sum unit_sales, sum store_cost", "country, gender", ""),
        listOf("sum unit sales by product for USA as country", "sum unit_sales", "product_id", "country = USA"),
        listOf("sum unit sales per products for USA as country", "sum unit_sales", "product_id", "country = USA"),
        listOf("sum unit sales for Club Chocolate Milk as product name", "sum unit_sales", "", "product_name = Club Chocolate Milk"),
        listOf("sum unit sales by month for Mexico as country", "sum unit_sales", "the_month", "country = Mexico"),
        listOf("sum unit sales by month", "sum unit_sales", "the_month", ""),
        listOf("store sales by year for Mexico as country", "avg store_sales", "the_year", "country = Mexico"),
        listOf("store sales by country for 1990 as year", "avg store_sales", "country", "the_year = 1990"),
        listOf("sum store cost by gender family for Mexico", "sum store_cost", "gender, product_family", "country = Mexico"),
        listOf("sum unit sales by category month country for 1990", "sum unit_sales", "product_category", "the_year = 1990"),
        listOf("store sales for type USA 1990", "avg store_sales", "gender, product_family", "country = USA, the_year = 1990"),
        listOf("store sales by family for 1990 as year", "avg store_sales", "product_family", "the_year = 1990"),
        listOf("average store sales for 1991 as year", "avg store_sales", "", "the_year = 1991"),
        listOf("store sales by province for 1990 as year", "avg store_sales", "state_province", "the_year = 1990"),
        listOf("store sales for Sheri Nowmer as customer", "avg store_sales", "", "fullname = Sheri Nowmer"),
        listOf("sum store cost by province", "sum store_cost", "state_province", ""),
        listOf("sum store cost per province", "sum store_cost", "state_province", ""),
        listOf("sum unit sales by coun", "sum unit_sales", "country", ""),
        listOf("sum unit sales store sales by product", "sum unit_sales, avg store_sales", "product_id", ""),
        listOf("sum unit sales by family for Jalisco", "sum unit_sales", "product_family", "state_province = Jalisco"),
        listOf("sum unit salies by category for canada as Country", "sum unit_sales", "product_category", "country = Canada"),
        listOf("sum unit salies by category for cana as Country", "sum unit_sales", "product_category", "country = Canada"),
        listOf("sum unit salies by category for usa as Country", "sum unit_sales", "product_category", "country = USA"),
        listOf("store sales by department Jalisco", "avg store_sales", "product_department", "state_province = Jalisco"),
        listOf("count sales by family", "count sales_fact_1997", "product_family", ""),
        listOf("count sales for Club Chocolate Milk as product name", "count sales_fact_1997", "", "product_name = Club Chocolate Milk"),
        listOf("count sales by city for Club Chocolate Milk as product name", "count sales_fact_1997", "city", "product_name = Club Chocolate Milk"),
        listOf("count sales by city", "count sales_fact_1997", "city", ""),
        listOf("sum unit sales by product for 2015 as year", "sum unit_sales", "product_id", "the_year = 2015"),
        listOf("sum unit sales growth for 2015 as year by product", "sum unit_sales", "product_id", "the_year = 2015"),
        listOf("sum unit sales growth for 2013 as year by product", "sum unit_sales", "product_id", "the_year = 2013"),
        listOf("sum unit sales growth for 2014 as year by product", "sum unit_sales", "product_id", "the_year = 2014"),
        listOf("sum unit sales growth for 2014 as year by category", "sum unit_sales", "product_category", "the_year = 2014"),
        listOf("sum unit sales by category for mexico", "sum unit_sales", "product_category", "country = Mexico"),
        listOf("sum unit sales by category for mexico as country", "sum unit_sales", "product_category", "country = Mexico"),
        listOf("sum unit sales by category for messico as Country", "sum unit_sales", "product_category", "country = Mexico"),
        listOf("store sales by month for club choc as product", "avg store_sales", "the_month", "product_name = Club Chocolate Milk"),
        listOf("store sales by month for club chocolate milk as product", "avg store_sales", "the_month", "product_name = Club Chocolate Milk"),
        listOf("count sales by month for Jalisco as Province", "count sales_fact_1997", "the_month", "state_province = Jalisco"),
        listOf("store_cost by province for 2013", "sum store_cost", "state_province", "the_year = 2013"),
        listOf("sum unit sales by yeat for atomc mints as product", "sum unit_sales", "the_year", "product_name = Atomic Mints"),
        listOf("sum unit sales by yeat for atmoc mints as product name", "sum unit_sales", "the_year", "product_name = Atomic Mints"),
        listOf("sum unit sales for Sheri Nowmer", "sum unit_sales", "", "fullname = Sheri Nowmer"),
        listOf("store sales by media type for Sheri Nowmer", "avg store_sales", "media_type", "fullname = Sheri Nowmer"),
        listOf("sum store cost by product name for Canada as country", "sum store_cost", "product_name", "country = Canada"),
        listOf("sum store cost by product for Canada as country", "sum store_cost", "product_name", "country = Canada"),
        listOf("sum stpre cost by media", "sum store_cost", "media_type", ""),
        listOf("sum store cst by media for Nowmer as customer", "sum store_cost", "media_type", "fullname = Sheri Nowmer"),
        listOf("sum unit sales by year Sheri Nowmer", "sum unit_sales", "the_year", "fullname = Sheri Nowmer"),
        listOf("sum unt sls by product for Sheri Nowmer as fullname", "sum unit_sales", "product_id", "fullname = Sheri Nowmer"),
        listOf("sum unit sales by prdct for Sheri Nowmer as fullname", "sum unit_sales", "product_id", "fullname = Sheri Nowmer"),
        listOf("sum unit sales by product for Seri Nower as fullname", "sum unit_sales", "product_id", "fullname = Sheri Nowmer"),
        listOf("sum unit sales by media type for USA", "sum unit_sales", "media_type", "country = USA"),
        listOf("sum unit sales by media type for USA and Mexico", "sum unit_sales", "media_type", "country = USA and country = Mexico"),
        listOf("sum unit sales by media type for Salem", "sum unit_sales", "media_type", "city = Salem"),
        listOf("sum unit sales by country by month by province for USA", "sum unit_sales", "country, the_month, state_province", "country = USA"),
        listOf("sum unit sales by month for USA", "sum unit_sales", "the_month", "country = USA"),
        listOf("sum unit sales for country Sheri Nowmer", "sum unit_sales", "", "country = USA"),
        listOf("store sales for Sheri Nowmer", "avg store_sales", "", "fullname = Sheri Nowmer"),
        listOf("store sales for USA", "avg store_sales", "", "country = USA"),
        listOf("store sales for USA and state province Sheri Nowmere", "avg store_sales", "", "country = USA and state_province = BC"),
        listOf("store sales for USA and Sheri Nowmere as province", "avg store_sales", "", "country = USA and state_province = BC"),
)

val dictionary = mapOf(
        "atomic mints" to "almond antique",
        "country" to "nation",
        "atmoc mints" to "almd antque",
        "atomc mints" to "almon antiqu",
        "unit sales" to "revenue",
        "unit_sales" to "revenue",
        "unit salies" to "reveniue",
        "unt sls" to "reve",
        "department" to "address",
        "store sales" to "extended price",
        "store cost" to "supply cost",
        "store cost" to "supply cost",
        "store_cost" to "supply cost",
        "stpre cost" to "sopply cost",
        "store cst" to "supp cost",
        "Sheri Nowmer" to "Apolonia Gerlach",
        "seri nower" to "Aplonia Gerach",
        "nowmer" to "Gerlach",
        "province" to "region",
        "media type" to "category",
        "media" to "category",
        "club chocolate milk" to "pale chocolate",
        "club choc" to "pal choc",
        "salem" to "vietnam",
        "USA" to "united states",
        "mexico" to "morocco",
        "fullname" to "customer",
        "gender" to "city",
        "state" to "nation",
        "family" to "address",
        "jalisco" to "africa",
        "store" to "supplier"
)

fun main() {
    queries.map { q ->
        println(
                q.map { qq ->
                    var nl = qq.toLowerCase()
                    dictionary.forEach { (k, v) -> nl = nl.replace(k.toLowerCase(), v) }
                    nl
                }.joinToString(";")
        )
    }
}